var bs_data=[
    {
        "desc":"NODE_6_length_199844_cov_113.724314",
        "end":62804,
        "id":"HQB-267_c00006_NODE_6_...region003",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":40.6,
                        "code":"PF08281",
                        "end":182,
                        "start":129
                    },
                    {
                        "bitscore":40.1,
                        "code":"PF04542",
                        "end":99,
                        "start":32
                    }
                ],
                "end":1129,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF1",
                "start":565,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":209.5,
                        "code":"PF14339",
                        "end":254,
                        "start":32
                    }
                ],
                "end":2111,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF2",
                "start":1331,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":41.7,
                        "code":"PF01810",
                        "end":190,
                        "start":12
                    }
                ],
                "end":2737,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF3",
                "start":2158,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":61.3,
                        "code":"PF13412",
                        "end":48,
                        "start":1
                    },
                    {
                        "bitscore":59.5,
                        "code":"PF01037",
                        "end":141,
                        "start":67
                    }
                ],
                "end":3284,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF4",
                "start":2840,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":45.8,
                        "code":"PF00583",
                        "end":138,
                        "start":19
                    }
                ],
                "end":3834,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF5",
                "start":3336,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":387.1,
                        "code":"PF20510",
                        "end":299,
                        "start":28
                    },
                    {
                        "bitscore":227.9,
                        "code":"PF04209",
                        "end":452,
                        "start":300
                    }
                ],
                "end":5322,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF6",
                "start":3942,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":73.1,
                        "code":"PF09298",
                        "end":115,
                        "start":26
                    },
                    {
                        "bitscore":183.8,
                        "code":"PF01557",
                        "end":401,
                        "start":119
                    }
                ],
                "end":6536,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF7",
                "start":5318,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":184.9,
                        "code":"PF02423",
                        "end":307,
                        "start":42
                    }
                ],
                "end":7456,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF8",
                "start":6532,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":211.6,
                        "code":"PF00370",
                        "end":242,
                        "start":2
                    },
                    {
                        "bitscore":110.8,
                        "code":"PF02782",
                        "end":436,
                        "start":251
                    }
                ],
                "end":9023,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF9",
                "start":7574,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":37.6,
                        "code":"PF00196",
                        "end":199,
                        "start":143
                    },
                    {
                        "bitscore":55.2,
                        "code":"PF03472",
                        "end":143,
                        "start":26
                    }
                ],
                "end":9644,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF10",
                "start":9026,
                "strand":-1
            },
            {
                "domains":[],
                "end":9989,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF11",
                "start":9779,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":44.3,
                        "code":"PF00765",
                        "end":128,
                        "start":17
                    }
                ],
                "end":10609,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF12",
                "start":10000,
                "strand":1
            },
            {
                "domains":[],
                "end":12117,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF13",
                "start":10605,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":70.8,
                        "code":"PF00005",
                        "end":153,
                        "start":17
                    }
                ],
                "end":12766,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF14",
                "start":12109,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":189.1,
                        "code":"PF12974",
                        "end":273,
                        "start":28
                    }
                ],
                "end":13633,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF15",
                "start":12769,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":61.9,
                        "code":"PF04879",
                        "end":108,
                        "start":47
                    }
                ],
                "end":14483,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF16",
                "start":13883,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":81.1,
                        "code":"PF00384",
                        "end":382,
                        "start":1
                    },
                    {
                        "bitscore":55.3,
                        "code":"PF01568",
                        "end":798,
                        "start":679
                    }
                ],
                "end":16964,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF17",
                "start":14531,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":74.7,
                        "code":"PF13247",
                        "end":209,
                        "start":111
                    },
                    {
                        "bitscore":52.4,
                        "code":"PF09163",
                        "end":308,
                        "start":266
                    }
                ],
                "end":17956,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF18",
                "start":16960,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":95.2,
                        "code":"PF01292",
                        "end":201,
                        "start":24
                    }
                ],
                "end":18645,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF19",
                "start":17955,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":284.7,
                        "code":"PF04216",
                        "end":302,
                        "start":16
                    }
                ],
                "end":19615,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF20",
                "start":18700,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":23.8,
                        "code":"PF12390",
                        "end":41,
                        "start":4
                    },
                    {
                        "bitscore":523.9,
                        "code":"PF03841",
                        "end":442,
                        "start":76
                    }
                ],
                "end":20973,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF21",
                "start":19614,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":92.6,
                        "code":"PF00009",
                        "end":167,
                        "start":1
                    },
                    {
                        "bitscore":31.0,
                        "code":"PF03144",
                        "end":260,
                        "start":191
                    },
                    {
                        "bitscore":52.2,
                        "code":"PF09106",
                        "end":488,
                        "start":432
                    },
                    {
                        "bitscore":58.6,
                        "code":"PF09107",
                        "end":619,
                        "start":573
                    }
                ],
                "end":22856,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF22",
                "start":20969,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":81.5,
                        "code":"PF01037",
                        "end":145,
                        "start":71
                    },
                    {
                        "bitscore":56.6,
                        "code":"PF13404",
                        "end":46,
                        "start":5
                    }
                ],
                "end":23317,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF23",
                "start":22852,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":147.9,
                        "code":"PF14850",
                        "end":164,
                        "start":53
                    },
                    {
                        "bitscore":287.7,
                        "code":"PF01619",
                        "end":465,
                        "start":173
                    },
                    {
                        "bitscore":365.0,
                        "code":"PF00171",
                        "end":973,
                        "start":537
                    }
                ],
                "end":26819,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF24",
                "start":23423,
                "strand":1
            },
            {
                "domains":[],
                "end":27823,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF25",
                "start":26860,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":41.5,
                        "code":"PF00012",
                        "end":232,
                        "start":7
                    }
                ],
                "end":29191,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF26",
                "start":27949,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":101.5,
                        "code":"PF17201",
                        "end":203,
                        "start":31
                    },
                    {
                        "bitscore":35.0,
                        "code":"PF00672",
                        "end":271,
                        "start":218
                    },
                    {
                        "bitscore":159.1,
                        "code":"PF00015",
                        "end":567,
                        "start":409
                    }
                ],
                "end":31260,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF27",
                "start":29328,
                "strand":1
            },
            {
                "domains":[],
                "end":31834,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF28",
                "start":31477,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":128.4,
                        "code":"PF00487",
                        "end":313,
                        "start":55
                    }
                ],
                "end":33099,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF29",
                "start":32061,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":164.6,
                        "code":"PF13403",
                        "end":323,
                        "start":176
                    }
                ],
                "end":34251,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF30",
                "start":33111,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":110.4,
                        "code":"PF13692",
                        "end":374,
                        "start":236
                    }
                ],
                "end":35943,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF31",
                "start":34698,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":117.8,
                        "code":"PF00668",
                        "end":439,
                        "start":19
                    },
                    {
                        "bitscore":255.6,
                        "code":"PF00501",
                        "end":852,
                        "start":459
                    },
                    {
                        "bitscore":24.5,
                        "code":"PF13193",
                        "end":930,
                        "start":860
                    },
                    {
                        "bitscore":44.5,
                        "code":"PF00550",
                        "end":1019,
                        "start":956
                    },
                    {
                        "bitscore":38.6,
                        "code":"PF00975",
                        "end":1280,
                        "start":1041
                    }
                ],
                "end":39948,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF32",
                "start":36069,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":134.8,
                        "code":"PF03808",
                        "end":230,
                        "start":60
                    }
                ],
                "end":40706,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF33",
                "start":39947,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":45.5,
                        "code":"PF00534",
                        "end":359,
                        "start":195
                    }
                ],
                "end":41866,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF34",
                "start":40702,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":160.1,
                        "code":"PF13440",
                        "end":337,
                        "start":42
                    }
                ],
                "end":43188,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF35",
                "start":41862,
                "strand":-1
            },
            {
                "domains":[],
                "end":44102,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF36",
                "start":43193,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":91.6,
                        "code":"PF00106",
                        "end":178,
                        "start":3
                    }
                ],
                "end":44839,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF37",
                "start":44098,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":67.4,
                        "code":"PF05199",
                        "end":513,
                        "start":396
                    },
                    {
                        "bitscore":34.4,
                        "code":"PF00732",
                        "end":283,
                        "start":9
                    }
                ],
                "end":46413,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF38",
                "start":44835,
                "strand":-1
            },
            {
                "domains":[],
                "end":47992,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF39",
                "start":46519,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":221.9,
                        "code":"PF00109",
                        "end":259,
                        "start":8
                    },
                    {
                        "bitscore":132.8,
                        "code":"PF02801",
                        "end":385,
                        "start":267
                    },
                    {
                        "bitscore":59.8,
                        "code":"PF16197",
                        "end":502,
                        "start":387
                    },
                    {
                        "bitscore":125.8,
                        "code":"PF00698",
                        "end":854,
                        "start":534
                    },
                    {
                        "bitscore":136.1,
                        "code":"PF08659",
                        "end":1348,
                        "start":1154
                    },
                    {
                        "bitscore":122.2,
                        "code":"PF14765",
                        "end":1647,
                        "start":1370
                    },
                    {
                        "bitscore":50.7,
                        "code":"PF00550",
                        "end":1806,
                        "start":1742
                    },
                    {
                        "bitscore":76.5,
                        "code":"PF00975",
                        "end":2088,
                        "start":1847
                    }
                ],
                "end":54426,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF40",
                "start":48099,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":62.5,
                        "code":"PF13641",
                        "end":267,
                        "start":4
                    }
                ],
                "end":55400,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF41",
                "start":54422,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":46.2,
                        "code":"PF00551",
                        "end":157,
                        "start":48
                    },
                    {
                        "bitscore":165.8,
                        "code":"PF00501",
                        "end":737,
                        "start":530
                    },
                    {
                        "bitscore":148.7,
                        "code":"PF00296",
                        "end":1079,
                        "start":753
                    },
                    {
                        "bitscore":142.9,
                        "code":"PF00501",
                        "end":1292,
                        "start":1101
                    },
                    {
                        "bitscore":34.5,
                        "code":"PF13193",
                        "end":1372,
                        "start":1300
                    },
                    {
                        "bitscore":43.2,
                        "code":"PF00550",
                        "end":1481,
                        "start":1416
                    }
                ],
                "end":59989,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF42",
                "start":55396,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":59.9,
                        "code":"PF00535",
                        "end":180,
                        "start":20
                    }
                ],
                "end":61020,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF43",
                "start":60024,
                "strand":-1
            },
            {
                "domains":[],
                "end":61762,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF44",
                "start":61231,
                "strand":1
            },
            {
                "domains":[],
                "end":62803,
                "id":"HQB-267_c00006_NODE_6_...region003_ORF45",
                "start":61762,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"NODE_2_length_899319_cov_130.793906",
        "end":47515,
        "id":"HQB-347_c00002_NODE_2_...region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":39.4,
                        "code":"PF00132",
                        "end":126,
                        "start":91
                    }
                ],
                "end":2000,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF1",
                "start":1427,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":38.5,
                        "code":"PF05159",
                        "end":116,
                        "start":54
                    },
                    {
                        "bitscore":100.5,
                        "code":"PF05159",
                        "end":295,
                        "start":110
                    }
                ],
                "end":3019,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF2",
                "start":1996,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":103.6,
                        "code":"PF01380",
                        "end":169,
                        "start":36
                    },
                    {
                        "bitscore":24.3,
                        "code":"PF00571",
                        "end":309,
                        "start":263
                    }
                ],
                "end":3988,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF3",
                "start":3058,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":88.8,
                        "code":"PF02878",
                        "end":137,
                        "start":12
                    },
                    {
                        "bitscore":33.8,
                        "code":"PF02879",
                        "end":256,
                        "start":158
                    },
                    {
                        "bitscore":42.4,
                        "code":"PF02880",
                        "end":379,
                        "start":260
                    },
                    {
                        "bitscore":29.0,
                        "code":"PF00408",
                        "end":471,
                        "start":373
                    }
                ],
                "end":5597,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF4",
                "start":4169,
                "strand":1
            },
            {
                "domains":[],
                "end":6452,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF5",
                "start":5627,
                "strand":-1
            },
            {
                "domains":[],
                "end":7170,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF6",
                "start":6651,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":241.3,
                        "code":"PF01583",
                        "end":616,
                        "start":460
                    },
                    {
                        "bitscore":141.3,
                        "code":"PF00009",
                        "end":337,
                        "start":22
                    }
                ],
                "end":9141,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF7",
                "start":7239,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":210.3,
                        "code":"PF01507",
                        "end":552,
                        "start":324
                    }
                ],
                "end":10934,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF8",
                "start":9140,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":168.7,
                        "code":"PF03600",
                        "end":535,
                        "start":9
                    }
                ],
                "end":12912,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF9",
                "start":11148,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":172.1,
                        "code":"PF00459",
                        "end":261,
                        "start":3
                    }
                ],
                "end":13779,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF10",
                "start":12978,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":119.5,
                        "code":"PF05159",
                        "end":321,
                        "start":56
                    }
                ],
                "end":14988,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF11",
                "start":13890,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":123.8,
                        "code":"PF00106",
                        "end":194,
                        "start":2
                    }
                ],
                "end":15807,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF12",
                "start":15048,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":67.7,
                        "code":"PF00884",
                        "end":513,
                        "start":233
                    }
                ],
                "end":17433,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF13",
                "start":15810,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":268.1,
                        "code":"PF05159",
                        "end":381,
                        "start":73
                    }
                ],
                "end":18655,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF14",
                "start":17383,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":172.7,
                        "code":"PF00155",
                        "end":436,
                        "start":92
                    }
                ],
                "end":20001,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF15",
                "start":18675,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":45.7,
                        "code":"PF00550",
                        "end":2474,
                        "start":2408
                    },
                    {
                        "bitscore":198.5,
                        "code":"PF08659",
                        "end":2306,
                        "start":2127
                    },
                    {
                        "bitscore":69.3,
                        "code":"PF00107",
                        "end":2064,
                        "start":1930
                    },
                    {
                        "bitscore":151.3,
                        "code":"PF14765",
                        "end":1167,
                        "start":887
                    },
                    {
                        "bitscore":216.1,
                        "code":"PF00698",
                        "end":843,
                        "start":525
                    },
                    {
                        "bitscore":71.3,
                        "code":"PF16197",
                        "end":490,
                        "start":376
                    },
                    {
                        "bitscore":127.2,
                        "code":"PF02801",
                        "end":374,
                        "start":258
                    },
                    {
                        "bitscore":262.2,
                        "code":"PF00109",
                        "end":250,
                        "start":2
                    }
                ],
                "end":27515,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF16",
                "start":20000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":65.7,
                        "code":"PF04545",
                        "end":605,
                        "start":552
                    },
                    {
                        "bitscore":100.8,
                        "code":"PF04539",
                        "end":540,
                        "start":463
                    },
                    {
                        "bitscore":75.9,
                        "code":"PF04542",
                        "end":454,
                        "start":384
                    },
                    {
                        "bitscore":208.8,
                        "code":"PF04546",
                        "end":353,
                        "start":139
                    },
                    {
                        "bitscore":48.2,
                        "code":"PF00140",
                        "end":131,
                        "start":98
                    },
                    {
                        "bitscore":101.5,
                        "code":"PF03979",
                        "end":85,
                        "start":5
                    }
                ],
                "end":29683,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF17",
                "start":27826,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.0,
                        "code":"PF08278",
                        "end":612,
                        "start":488
                    },
                    {
                        "bitscore":41.9,
                        "code":"PF10410",
                        "end":423,
                        "start":368
                    },
                    {
                        "bitscore":62.8,
                        "code":"PF13155",
                        "end":349,
                        "start":261
                    },
                    {
                        "bitscore":138.6,
                        "code":"PF08275",
                        "end":251,
                        "start":123
                    },
                    {
                        "bitscore":133.6,
                        "code":"PF01807",
                        "end":102,
                        "start":5
                    }
                ],
                "end":31729,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF18",
                "start":29872,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":185.2,
                        "code":"PF09424",
                        "end":147,
                        "start":5
                    }
                ],
                "end":32229,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF19",
                "start":31779,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":80.1,
                        "code":"PF01165",
                        "end":57,
                        "start":3
                    }
                ],
                "end":32537,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF20",
                "start":32321,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":339.0,
                        "code":"PF00814",
                        "end":345,
                        "start":57
                    }
                ],
                "end":33763,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF21",
                "start":32602,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":113.6,
                        "code":"PF02152",
                        "end":113,
                        "start":4
                    }
                ],
                "end":34119,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF22",
                "start":33762,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":88.0,
                        "code":"PF01288",
                        "end":130,
                        "start":5
                    }
                ],
                "end":34646,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF23",
                "start":34118,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":38.3,
                        "code":"PF12627",
                        "end":213,
                        "start":149
                    },
                    {
                        "bitscore":69.1,
                        "code":"PF01743",
                        "end":122,
                        "start":3
                    }
                ],
                "end":35789,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF24",
                "start":34679,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":60.7,
                        "code":"PF00581",
                        "end":98,
                        "start":8
                    }
                ],
                "end":36109,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF25",
                "start":35791,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":48.5,
                        "code":"PF00149",
                        "end":226,
                        "start":1
                    }
                ],
                "end":36946,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF26",
                "start":36130,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":115.8,
                        "code":"PF04379",
                        "end":107,
                        "start":21
                    }
                ],
                "end":37361,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF27",
                "start":36971,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":228.0,
                        "code":"PF00398",
                        "end":267,
                        "start":8
                    }
                ],
                "end":38177,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF28",
                "start":37364,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":355.4,
                        "code":"PF04166",
                        "end":321,
                        "start":30
                    }
                ],
                "end":39241,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF29",
                "start":38242,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":103.4,
                        "code":"PF13616",
                        "end":392,
                        "start":285
                    },
                    {
                        "bitscore":71.4,
                        "code":"PF00639",
                        "end":282,
                        "start":188
                    },
                    {
                        "bitscore":126.5,
                        "code":"PF09312",
                        "end":153,
                        "start":36
                    }
                ],
                "end":40545,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF30",
                "start":39237,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":285.7,
                        "code":"PF04453",
                        "end":699,
                        "start":332
                    },
                    {
                        "bitscore":34.7,
                        "code":"PF03968",
                        "end":228,
                        "start":95
                    }
                ],
                "end":42880,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF31",
                "start":40522,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":106.9,
                        "code":"PF01636",
                        "end":269,
                        "start":28
                    }
                ],
                "end":44049,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF32",
                "start":43005,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":89.8,
                        "code":"PF00483",
                        "end":233,
                        "start":2
                    }
                ],
                "end":44756,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF33",
                "start":44045,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":62.5,
                        "code":"PF05099",
                        "end":186,
                        "start":68
                    },
                    {
                        "bitscore":50.1,
                        "code":"PF00226",
                        "end":283,
                        "start":218
                    }
                ],
                "end":45597,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF34",
                "start":44745,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":158.8,
                        "code":"PF12048",
                        "end":351,
                        "start":9
                    }
                ],
                "end":46753,
                "id":"HQB-347_c00002_NODE_2_...region001_ORF35",
                "start":45622,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Chr1",
        "end":41958,
        "id":"HQB-458_Chr1.region006",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":121.6,
                        "code":"PF00590",
                        "end":209,
                        "start":2
                    }
                ],
                "end":744,
                "id":"HQB-458_Chr1.region006_ORF1",
                "start":1,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":87.8,
                        "code":"PF00590",
                        "end":222,
                        "start":2
                    }
                ],
                "end":1493,
                "id":"HQB-458_Chr1.region006_ORF2",
                "start":740,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":62.6,
                        "code":"PF13450",
                        "end":92,
                        "start":23
                    },
                    {
                        "bitscore":271.0,
                        "code":"PF03275",
                        "end":377,
                        "start":167
                    }
                ],
                "end":2769,
                "id":"HQB-458_Chr1.region006_ORF3",
                "start":1539,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":223.8,
                        "code":"PF17994",
                        "end":164,
                        "start":23
                    },
                    {
                        "bitscore":105.0,
                        "code":"PF13641",
                        "end":428,
                        "start":170
                    },
                    {
                        "bitscore":279.0,
                        "code":"PF19320",
                        "end":633,
                        "start":439
                    }
                ],
                "end":4676,
                "id":"HQB-458_Chr1.region006_ORF4",
                "start":2768,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":50.9,
                        "code":"PF01569",
                        "end":178,
                        "start":67
                    }
                ],
                "end":5190,
                "id":"HQB-458_Chr1.region006_ORF5",
                "start":4653,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":71.3,
                        "code":"PF01040",
                        "end":278,
                        "start":32
                    }
                ],
                "end":6092,
                "id":"HQB-458_Chr1.region006_ORF6",
                "start":5186,
                "strand":1
            },
            {
                "domains":[],
                "end":7950,
                "id":"HQB-458_Chr1.region006_ORF7",
                "start":6069,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":162.7,
                        "code":"PF00756",
                        "end":325,
                        "start":56
                    }
                ],
                "end":9145,
                "id":"HQB-458_Chr1.region006_ORF8",
                "start":8152,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":143.7,
                        "code":"PF00756",
                        "end":398,
                        "start":132
                    }
                ],
                "end":10525,
                "id":"HQB-458_Chr1.region006_ORF9",
                "start":9310,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":152.5,
                        "code":"PF00756",
                        "end":359,
                        "start":89
                    },
                    {
                        "bitscore":39.5,
                        "code":"PF08310",
                        "end":438,
                        "start":388
                    },
                    {
                        "bitscore":78.3,
                        "code":"PF08310",
                        "end":492,
                        "start":440
                    },
                    {
                        "bitscore":56.5,
                        "code":"PF08310",
                        "end":546,
                        "start":494
                    },
                    {
                        "bitscore":66.3,
                        "code":"PF08310",
                        "end":601,
                        "start":548
                    }
                ],
                "end":12654,
                "id":"HQB-458_Chr1.region006_ORF10",
                "start":10737,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":31.9,
                        "code":"PF05305",
                        "end":197,
                        "start":113
                    }
                ],
                "end":13359,
                "id":"HQB-458_Chr1.region006_ORF11",
                "start":12765,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":54.6,
                        "code":"PF01083",
                        "end":263,
                        "start":57
                    }
                ],
                "end":14325,
                "id":"HQB-458_Chr1.region006_ORF12",
                "start":13371,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":182.4,
                        "code":"PF00296",
                        "end":316,
                        "start":20
                    }
                ],
                "end":15533,
                "id":"HQB-458_Chr1.region006_ORF13",
                "start":14513,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":239.9,
                        "code":"PF00501",
                        "end":491,
                        "start":27
                    }
                ],
                "end":17587,
                "id":"HQB-458_Chr1.region006_ORF14",
                "start":15688,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":43.6,
                        "code":"PF00550",
                        "end":102,
                        "start":36
                    },
                    {
                        "bitscore":279.8,
                        "code":"PF00109",
                        "end":376,
                        "start":128
                    },
                    {
                        "bitscore":137.0,
                        "code":"PF02801",
                        "end":502,
                        "start":384
                    },
                    {
                        "bitscore":43.7,
                        "code":"PF16197",
                        "end":653,
                        "start":504
                    },
                    {
                        "bitscore":210.0,
                        "code":"PF00698",
                        "end":1016,
                        "start":691
                    },
                    {
                        "bitscore":28.3,
                        "code":"PF00550",
                        "end":1252,
                        "start":1187
                    },
                    {
                        "bitscore":77.9,
                        "code":"PF00975",
                        "end":1547,
                        "start":1428
                    }
                ],
                "end":22704,
                "id":"HQB-458_Chr1.region006_ORF15",
                "start":17640,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":489.1,
                        "code":"PF01039",
                        "end":512,
                        "start":30
                    }
                ],
                "end":24253,
                "id":"HQB-458_Chr1.region006_ORF16",
                "start":22708,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":564.3,
                        "code":"PF14896",
                        "end":1099,
                        "start":713
                    },
                    {
                        "bitscore":727.0,
                        "code":"PF04602",
                        "end":675,
                        "start":217
                    },
                    {
                        "bitscore":179.8,
                        "code":"PF17689",
                        "end":213,
                        "start":55
                    }
                ],
                "end":27903,
                "id":"HQB-458_Chr1.region006_ORF17",
                "start":24591,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":531.6,
                        "code":"PF14896",
                        "end":1048,
                        "start":672
                    },
                    {
                        "bitscore":703.2,
                        "code":"PF04602",
                        "end":641,
                        "start":181
                    },
                    {
                        "bitscore":125.4,
                        "code":"PF17689",
                        "end":177,
                        "start":39
                    }
                ],
                "end":31143,
                "id":"HQB-458_Chr1.region006_ORF18",
                "start":27990,
                "strand":-1
            },
            {
                "domains":[],
                "end":32909,
                "id":"HQB-458_Chr1.region006_ORF19",
                "start":31166,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":242.5,
                        "code":"PF12249",
                        "end":647,
                        "start":476
                    },
                    {
                        "bitscore":543.6,
                        "code":"PF12250",
                        "end":470,
                        "start":10
                    }
                ],
                "end":34894,
                "id":"HQB-458_Chr1.region006_ORF20",
                "start":32944,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":88.0,
                        "code":"PF00106",
                        "end":205,
                        "start":10
                    }
                ],
                "end":35659,
                "id":"HQB-458_Chr1.region006_ORF21",
                "start":34894,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":32.4,
                        "code":"PF04030",
                        "end":480,
                        "start":407
                    },
                    {
                        "bitscore":88.1,
                        "code":"PF01565",
                        "end":184,
                        "start":42
                    }
                ],
                "end":37107,
                "id":"HQB-458_Chr1.region006_ORF22",
                "start":35655,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":62.8,
                        "code":"PF04138",
                        "end":142,
                        "start":26
                    }
                ],
                "end":37673,
                "id":"HQB-458_Chr1.region006_ORF23",
                "start":37235,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":201.9,
                        "code":"PF00908",
                        "end":183,
                        "start":5
                    }
                ],
                "end":38279,
                "id":"HQB-458_Chr1.region006_ORF24",
                "start":37694,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":216.7,
                        "code":"PF00483",
                        "end":238,
                        "start":2
                    }
                ],
                "end":39148,
                "id":"HQB-458_Chr1.region006_ORF25",
                "start":38275,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":252.6,
                        "code":"PF16363",
                        "end":336,
                        "start":25
                    }
                ],
                "end":40257,
                "id":"HQB-458_Chr1.region006_ORF26",
                "start":39156,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":76.5,
                        "code":"PF03706",
                        "end":300,
                        "start":14
                    }
                ],
                "end":41236,
                "id":"HQB-458_Chr1.region006_ORF27",
                "start":40264,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":37.7,
                        "code":"PF13720",
                        "end":236,
                        "start":170
                    },
                    {
                        "bitscore":36.5,
                        "code":"PF00132",
                        "end":37,
                        "start":4
                    }
                ],
                "end":41958,
                "id":"HQB-458_Chr1.region006_ORF28",
                "start":41232,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Chr1",
        "end":46447,
        "id":"HQB-458_Chr1.region008",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":67.5,
                        "code":"PF16320",
                        "end":55,
                        "start":5
                    },
                    {
                        "bitscore":97.0,
                        "code":"PF00542",
                        "end":128,
                        "start":61
                    }
                ],
                "end":705,
                "id":"HQB-458_Chr1.region008_ORF1",
                "start":318,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":96.4,
                        "code":"PF00005",
                        "end":169,
                        "start":20
                    }
                ],
                "end":2341,
                "id":"HQB-458_Chr1.region008_ORF2",
                "start":1096,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":227.9,
                        "code":"PF02405",
                        "end":254,
                        "start":43
                    }
                ],
                "end":3141,
                "id":"HQB-458_Chr1.region008_ORF3",
                "start":2346,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":200.2,
                        "code":"PF02405",
                        "end":274,
                        "start":63
                    }
                ],
                "end":4008,
                "id":"HQB-458_Chr1.region008_ORF4",
                "start":3147,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":37.9,
                        "code":"PF02470",
                        "end":117,
                        "start":39
                    },
                    {
                        "bitscore":225.8,
                        "code":"PF11887",
                        "end":343,
                        "start":121
                    }
                ],
                "end":5354,
                "id":"HQB-458_Chr1.region008_ORF5",
                "start":4004,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":46.8,
                        "code":"PF02470",
                        "end":113,
                        "start":36
                    },
                    {
                        "bitscore":92.9,
                        "code":"PF11887",
                        "end":338,
                        "start":117
                    }
                ],
                "end":6418,
                "id":"HQB-458_Chr1.region008_ORF6",
                "start":5350,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":61.8,
                        "code":"PF02470",
                        "end":110,
                        "start":35
                    },
                    {
                        "bitscore":50.0,
                        "code":"PF11887",
                        "end":330,
                        "start":112
                    }
                ],
                "end":7428,
                "id":"HQB-458_Chr1.region008_ORF7",
                "start":6414,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":55.8,
                        "code":"PF02470",
                        "end":116,
                        "start":40
                    },
                    {
                        "bitscore":54.2,
                        "code":"PF11887",
                        "end":325,
                        "start":120
                    }
                ],
                "end":8708,
                "id":"HQB-458_Chr1.region008_ORF8",
                "start":7427,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":55.5,
                        "code":"PF02470",
                        "end":125,
                        "start":47
                    },
                    {
                        "bitscore":72.9,
                        "code":"PF11887",
                        "end":361,
                        "start":130
                    }
                ],
                "end":10006,
                "id":"HQB-458_Chr1.region008_ORF9",
                "start":8704,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":52.8,
                        "code":"PF02470",
                        "end":115,
                        "start":38
                    },
                    {
                        "bitscore":33.4,
                        "code":"PF11887",
                        "end":396,
                        "start":118
                    }
                ],
                "end":11250,
                "id":"HQB-458_Chr1.region008_ORF10",
                "start":10002,
                "strand":1
            },
            {
                "domains":[],
                "end":12069,
                "id":"HQB-458_Chr1.region008_ORF11",
                "start":11376,
                "strand":1
            },
            {
                "domains":[],
                "end":13015,
                "id":"HQB-458_Chr1.region008_ORF12",
                "start":12133,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":280.1,
                        "code":"PF00202",
                        "end":435,
                        "start":33
                    }
                ],
                "end":15781,
                "id":"HQB-458_Chr1.region008_ORF13",
                "start":13222,
                "strand":1
            },
            {
                "domains":[],
                "end":16469,
                "id":"HQB-458_Chr1.region008_ORF14",
                "start":15845,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":102.5,
                        "code":"PF03176",
                        "end":712,
                        "start":407
                    },
                    {
                        "bitscore":149.1,
                        "code":"PF03176",
                        "end":380,
                        "start":53
                    }
                ],
                "end":18633,
                "id":"HQB-458_Chr1.region008_ORF15",
                "start":16458,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":149.0,
                        "code":"PF00155",
                        "end":439,
                        "start":94
                    }
                ],
                "end":19999,
                "id":"HQB-458_Chr1.region008_ORF16",
                "start":18655,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":37.6,
                        "code":"PF00550",
                        "end":2109,
                        "start":2050
                    },
                    {
                        "bitscore":179.8,
                        "code":"PF08659",
                        "end":1949,
                        "start":1768
                    },
                    {
                        "bitscore":66.6,
                        "code":"PF00107",
                        "end":1703,
                        "start":1575
                    },
                    {
                        "bitscore":170.9,
                        "code":"PF14765",
                        "end":1180,
                        "start":908
                    },
                    {
                        "bitscore":239.7,
                        "code":"PF00698",
                        "end":861,
                        "start":539
                    },
                    {
                        "bitscore":58.8,
                        "code":"PF16197",
                        "end":504,
                        "start":382
                    },
                    {
                        "bitscore":128.2,
                        "code":"PF02801",
                        "end":379,
                        "start":261
                    },
                    {
                        "bitscore":274.0,
                        "code":"PF00109",
                        "end":253,
                        "start":1
                    }
                ],
                "end":26447,
                "id":"HQB-458_Chr1.region008_ORF17",
                "start":20000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":87.8,
                        "code":"PF04561",
                        "end":366,
                        "start":168
                    },
                    {
                        "bitscore":96.7,
                        "code":"PF04565",
                        "end":493,
                        "start":425
                    },
                    {
                        "bitscore":88.8,
                        "code":"PF10385",
                        "end":569,
                        "start":503
                    },
                    {
                        "bitscore":522.6,
                        "code":"PF00562",
                        "end":1051,
                        "start":630
                    },
                    {
                        "bitscore":93.0,
                        "code":"PF04560",
                        "end":1129,
                        "start":1053
                    }
                ],
                "end":30882,
                "id":"HQB-458_Chr1.region008_ORF18",
                "start":27375,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":274.9,
                        "code":"PF04997",
                        "end":417,
                        "start":4
                    },
                    {
                        "bitscore":98.0,
                        "code":"PF00623",
                        "end":561,
                        "start":460
                    },
                    {
                        "bitscore":92.8,
                        "code":"PF04983",
                        "end":735,
                        "start":564
                    },
                    {
                        "bitscore":28.9,
                        "code":"PF05000",
                        "end":843,
                        "start":744
                    },
                    {
                        "bitscore":219.5,
                        "code":"PF04998",
                        "end":1218,
                        "start":842
                    }
                ],
                "end":34936,
                "id":"HQB-458_Chr1.region008_ORF19",
                "start":30979,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":50.6,
                        "code":"PF05199",
                        "end":545,
                        "start":437
                    }
                ],
                "end":36667,
                "id":"HQB-458_Chr1.region008_ORF20",
                "start":35002,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":59.9,
                        "code":"PF03372",
                        "end":317,
                        "start":108
                    }
                ],
                "end":37741,
                "id":"HQB-458_Chr1.region008_ORF21",
                "start":36760,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":31.7,
                        "code":"PF00903",
                        "end":115,
                        "start":4
                    }
                ],
                "end":38118,
                "id":"HQB-458_Chr1.region008_ORF22",
                "start":37752,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":138.1,
                        "code":"PF00296",
                        "end":295,
                        "start":2
                    }
                ],
                "end":39213,
                "id":"HQB-458_Chr1.region008_ORF23",
                "start":38226,
                "strand":1
            },
            {
                "domains":[],
                "end":39443,
                "id":"HQB-458_Chr1.region008_ORF24",
                "start":39239,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.8,
                        "code":"PF00300",
                        "end":81,
                        "start":7
                    }
                ],
                "end":39952,
                "id":"HQB-458_Chr1.region008_ORF25",
                "start":39439,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":116.3,
                        "code":"PF02632",
                        "end":186,
                        "start":42
                    }
                ],
                "end":40634,
                "id":"HQB-458_Chr1.region008_ORF26",
                "start":40049,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":44.6,
                        "code":"PF13193",
                        "end":355,
                        "start":282
                    }
                ],
                "end":41731,
                "id":"HQB-458_Chr1.region008_ORF27",
                "start":40630,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":165.1,
                        "code":"PF00108",
                        "end":245,
                        "start":5
                    },
                    {
                        "bitscore":112.1,
                        "code":"PF02803",
                        "end":372,
                        "start":250
                    }
                ],
                "end":42852,
                "id":"HQB-458_Chr1.region008_ORF28",
                "start":41727,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":94.5,
                        "code":"PF00005",
                        "end":164,
                        "start":20
                    }
                ],
                "end":43529,
                "id":"HQB-458_Chr1.region008_ORF29",
                "start":42845,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":45.2,
                        "code":"PF02361",
                        "end":203,
                        "start":8
                    }
                ],
                "end":44209,
                "id":"HQB-458_Chr1.region008_ORF30",
                "start":43525,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":110.8,
                        "code":"PF01643",
                        "end":256,
                        "start":23
                    }
                ],
                "end":45077,
                "id":"HQB-458_Chr1.region008_ORF31",
                "start":44285,
                "strand":-1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
